# Generated by Django 5.2.8 on 2025-11-08 07:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='batch_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Batch Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='invalid_pincode', message='PIN code must be 6 digits', regex='^\\d{6}$')], verbose_name='PIN Code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Subadmin', 'Subadmin'), ('Teacher', 'Teacher'), ('SME', 'SME'), ('Student', 'Student'), ('Blogger', 'Blogger')], default='Student', max_length=20, verbose_name='Role'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Mobile number must be 10 digits', regex='^\\d{10}$')], verbose_name='Mobile Number'),
        ),
    ]
