# Generated by Django 5.2.8 on 2025-11-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_batch_name_customuser_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subjects',
            field=models.CharField(blank=True, help_text='Comma-separated subjects (required for role=Teacher)', max_length=255, null=True, verbose_name='Subjects'),
        ),
    ]
