# Generated by Django 5.2.8 on 2025-11-09 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_mobile_number', message='Mobile number must be 10 digits', regex='^[0-9]{10}$')], verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(code='invalid_pincode', message='PIN code must be 6 digits', regex='^[0-9]{6}$')], verbose_name='PIN Code'),
        ),
    ]
