"""
Django settings for Dishom project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$16ll_s%ph=l-1-j67hs)$&!%$8!03s_h3z%@+f2#g9dbg!)^w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1']  


# Application definition

INSTALLED_APPS = [
    'jazzmin',  # Best UI for Django Admin
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'django_filters',  # For filtering in DRF viewsets
    'django_browser_reload',
    'accounts',
    'batch',
    'study',
    'Live_Class',
]

# Custom User Model
AUTH_USER_MODEL = 'accounts.CustomUser'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_FILTER_BACKENDS': (
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
}

# JWT settings
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
]

ROOT_URLCONF = 'Dishom.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Dishom.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Additional locations the staticfiles app will traverse
# We keep the project's `static/` folder (backend/static) here so
# your custom CSS/JS are discoverable by runserver and collectstatic.
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Directory where `collectstatic` will copy all static files for production
# (create this directory or ensure permissions when deploying)
STATIC_ROOT = BASE_DIR / 'staticfiles'


# Media files (user uploaded)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Safal",
    "site_header": "Safal   ",
    "site_brand": "Safal Admin", # Note the extra spaces for better appearance
    "welcome_sign": "Welcome to the Safal Admin",
    "copyright": "Safal 2025",
    "search_model": "accounts.CustomUser",
    "custom_css": False,
    "custom_js": False,
    "use_google_fonts_cdn": True,
    "icons": {
        # Users and Groups (built-in auth app)
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
        # Batches (custom app models)
        "batch.Batch": "fas fa-layer-group",
        # Optional other icons (left intact)
        "batch.Subject": "fas fa-book",
        "study.Study": "fas fa-book-reader",
        "accounts.CustomUser": "fas fa-user"
    },
    # Use horizontal tabs for admin change forms across all apps
    "changeform_format": "horizontal_tabs",
    # Ensure specific models use horizontal tabs
    "changeform_format_overrides": {
        "accounts.CustomUser": "horizontal_tabs",
        "study.Study": "horizontal_tabs",
    },
    # Add Dashboard shortcut with tachometer icon in the top menu
    "topmenu_links": [
        {"name": "Dashboard", "url": "admin:index", "icon": "fas fa-tachometer-alt"},
    ],
    # Hide specific models from the admin sidebar/menu
    "hide_models": [
        "batch.Chapter",
        "batch.CourseCategory",
    ],

    # App ordering preference in the sidebar
    "order_with_respect_to": ["study", "batch", "accounts", "auth"],
    # Explicit menu structure to control order and grouping
    "menu": [
        {"app": "study", "label": "Study"},
        {"app": "batch", "label": "Batch"},
        {
            "label": "Authentication and Authorization",
            "models": [
                "accounts.CustomUser",
                "auth.Group",
            ],
        },
    ]
}

# Email and frontend settings for development
# Use console email backend to print emails in the terminal during development
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'no-reply@example.com'
FRONTEND_BASE_URL = 'http://localhost:5173'

# CORS settings for frontend dev server
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
]
