# Generated by Django 5.2.8 on 2025-11-12 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Live_Class', '0001_initial'),
        ('batch', '0007_subject_sme_alter_subject_teachers'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='batch.batch', verbose_name='Batch'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='batch.chapter', verbose_name='Chapter'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='course_category',
            field=models.ForeignKey(blank=True, help_text='Select course to filter batches', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='batch.coursecategory', verbose_name='Course'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_sessions', to='batch.subject', verbose_name='Subject'),
        ),
    ]
