# Generated by Django 5.2.8 on 2025-11-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Live_Class', '0002_livesession_batch_livesession_chapter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livesession',
            name='live_platform',
            field=models.CharField(choices=[('videosdk', 'VideoSDK'), ('youtube', 'YouTube')], default='videosdk', max_length=20, verbose_name='Platform'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='videosdk_meeting_id',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='VideoSDK Meeting ID'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='videosdk_token',
            field=models.CharField(blank=True, help_text='Server-generated auth token (do not paste secret here).', max_length=256, null=True, verbose_name='VideoSDK Token'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='youtube_stream_key',
            field=models.CharField(blank=True, help_text='RTMP Stream Key (keep confidential)', max_length=128, null=True, verbose_name='YouTube Stream Key'),
        ),
        migrations.AddField(
            model_name='livesession',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='For scheduled live or existing video URL', null=True, verbose_name='YouTube Video URL'),
        ),
    ]
