# Generated by Django 5.2.8 on 2025-11-09 09:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_convert_fks_to_m2m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='course_category',
            field=models.CharField(choices=[('BCECE', 'BCECE'), ('DCECE', 'DCECE'), ('UG_BOTANY', 'UG BOTANY'), ('UG_ZOOLOGY', 'UG ZOOLOGY'), ('PG_BOTANY', 'PG BOTANY'), ('PG_ZOOLOGY', 'PG ZOOLOGY')], default='BCECE', help_text='Select a course category for this batch', max_length=100, verbose_name='Course Category'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='subjects',
            field=models.ManyToManyField(help_text='Select 1-10 subjects for this batch', related_name='batches', to='batch.subject', verbose_name='Subjects'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='teachers',
            field=models.ManyToManyField(help_text='Select 1-10 teachers for this batch', limit_choices_to={'role': 'Teacher'}, related_name='teaching_batches', to=settings.AUTH_USER_MODEL, verbose_name='Teachers'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='thumbnail',
            field=models.ImageField(help_text='Image should be approximately 300x700 pixels', upload_to='batches/', verbose_name='Batch Thumbnail'),
        ),
    ]
