# Generated by Django 5.2.8 on 2025-11-09 13:45

import django.db.models.deletion
from django.db import migrations, models


def populate_course_categories(apps, schema_editor):
    """Create CourseCategory records from existing choices."""
    CourseCategory = apps.get_model('batch', 'CourseCategory')
    
    categories = [
        {'name': 'BCECE', 'code': 'BCECE'},
        {'name': 'DCECE', 'code': 'DCECE'},
        {'name': 'UG BOTANY', 'code': 'UG_BOTANY'},
        {'name': 'UG ZOOLOGY', 'code': 'UG_ZOOLOGY'},
        {'name': 'PG BOTANY', 'code': 'PG_BOTANY'},
        {'name': 'PG ZOOLOGY', 'code': 'PG_ZOOLOGY'},
    ]
    
    for cat_data in categories:
        CourseCategory.objects.get_or_create(
            code=cat_data['code'],
            defaults={'name': cat_data['name']}
        )


def migrate_batch_data(apps, schema_editor):
    """Migrate existing Batch course_category CharField to ForeignKey."""
    Batch = apps.get_model('batch', 'Batch')
    CourseCategory = apps.get_model('batch', 'CourseCategory')
    
    # Use raw SQL to get old values and update new field
    from django.db import connection
    with connection.cursor() as cursor:
        # Get all batches with their old course_category values
        cursor.execute('SELECT id, course_category FROM batch_batch')
        rows = cursor.fetchall()
        
        for batch_id, old_value in rows:
            if old_value:
                try:
                    category = CourseCategory.objects.get(code=old_value)
                    # Update the temporary field
                    Batch.objects.filter(pk=batch_id).update(course_category_new_id=category.id)
                except CourseCategory.DoesNotExist:
                    # Default to BCECE if category not found
                    try:
                        default_cat = CourseCategory.objects.get(code='BCECE')
                        Batch.objects.filter(pk=batch_id).update(course_category_new_id=default_cat.id)
                    except:
                        pass


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('code', models.CharField(help_text='Unique code like BCECE, DCECE, etc.', max_length=50, unique=True, verbose_name='Category Code')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RunPython(populate_course_categories, migrations.RunPython.noop),
        # Add temporary field for ForeignKey
        migrations.AddField(
            model_name='batch',
            name='course_category_new',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='batches_temp',
                to='batch.coursecategory',
                verbose_name='Course Category (New)'
            ),
        ),
        # Migrate data
        migrations.RunPython(migrate_batch_data, migrations.RunPython.noop),
        # Remove old field
        migrations.RemoveField(
            model_name='batch',
            name='course_category',
        ),
        # Rename new field
        migrations.RenameField(
            model_name='batch',
            old_name='course_category_new',
            new_name='course_category',
        ),
        # Make it required
        migrations.AlterField(
            model_name='batch',
            name='course_category',
            field=models.ForeignKey(
                help_text='Select a course category for this batch',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='batches',
                to='batch.coursecategory',
                verbose_name='Course Category'
            ),
        ),
    ]
