# Generated by Django 5.2.8 on 2025-11-12 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0005_coursecategory_alter_batch_course_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(blank=True, help_text='Select teachers who teach this subject', limit_choices_to={'role': 'Teacher'}, related_name='teaches_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Teachers'),
        ),
    ]
