# Generated by Django 5.2.8 on 2025-11-12 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0006_subject_teachers'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='sme',
            field=models.ForeignKey(blank=True, help_text='Select the SME (primary subject matter expert)', limit_choices_to={'role': 'Teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sme_subjects', to=settings.AUTH_USER_MODEL, verbose_name='SME'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teachers',
            field=models.ManyToManyField(help_text='Select teachers who teach this subject', limit_choices_to={'role': 'Teacher'}, related_name='teaches_subjects', to=settings.AUTH_USER_MODEL, verbose_name='Teachers'),
        ),
    ]
