# Generated by Django 4.2.7 on 2025-11-09 13:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100, verbose_name='Batch Name')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Batch',
                'verbose_name_plural': 'Batches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_name', models.CharField(max_length=200, verbose_name='Chapter Name')),
                ('chapter_number', models.PositiveIntegerField(help_text='Sequential chapter number', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Chapter Number')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chapter',
                'verbose_name_plural': 'Chapters',
                'ordering': ['chapter_number', 'chapter_name'],
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Course Category',
                'verbose_name_plural': 'Course Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Video Title')),
                ('video_url', models.URLField(blank=True, help_text='URL to video (YouTube, Vimeo, etc.)', max_length=500, null=True, verbose_name='Video URL')),
                ('video_file', models.FileField(blank=True, help_text='Upload video file (if not using URL)', null=True, upload_to='study/videos/', verbose_name='Video File')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Video duration in seconds', null=True, verbose_name='Duration (seconds)')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='study.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, verbose_name='Subject Name')),
                ('subject_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Subject Code')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='study.batch', verbose_name='Batch')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
                'ordering': ['subject_name'],
                'unique_together': {('batch', 'subject_name')},
            },
        ),
        migrations.CreateModel(
            name='DPPPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='DPP PDF Title')),
                ('pdf_file', models.FileField(help_text='Upload PDF file', upload_to='study/dpp_pdfs/', verbose_name='PDF File')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpp_pdfs', to='study.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'DPP PDF',
                'verbose_name_plural': 'DPP PDFs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='DPP Title')),
                ('content', models.TextField(help_text='Text content or question set', verbose_name='DPP Content')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dpps', to='study.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'DPP',
                'verbose_name_plural': 'DPPs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Note Title')),
                ('note_file', models.FileField(help_text='Upload PDF or text file', upload_to='study/class_notes/', verbose_name='Note File')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=1, help_text='Display order', verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_notes', to='study.chapter', verbose_name='Chapter')),
            ],
            options={
                'verbose_name': 'Class Note',
                'verbose_name_plural': 'Class Notes',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='chapter',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='study.subject', verbose_name='Subject'),
        ),
        migrations.AddField(
            model_name='batch',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='study.coursecategory', verbose_name='Course Category'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('subject', 'chapter_number')},
        ),
    ]
