# Generated by Django 5.2.8 on 2025-11-09 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0004_chapter'),
        ('study', '0003_add_foreign_keys'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='description',
        ),
        migrations.AlterField(
            model_name='study',
            name='batch',
            field=models.ForeignKey(help_text='Select the batch for this study material', on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='batch.batch', verbose_name='Batch'),
        ),
        migrations.AlterField(
            model_name='study',
            name='chapter',
            field=models.ForeignKey(help_text='Select the chapter for this study material', on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='batch.chapter', verbose_name='Chapter'),
        ),
        migrations.AlterField(
            model_name='study',
            name='subject',
            field=models.ForeignKey(help_text='Select the subject for this study material', on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='batch.subject', verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='study',
            name='teacher',
            field=models.ForeignKey(help_text='Select the teacher for this study material', limit_choices_to={'role': 'Teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to=settings.AUTH_USER_MODEL, verbose_name='Teacher'),
        ),
    ]
