# Generated by Django 5.2.8 on 2025-11-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_remove_study_description_alter_study_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='course_category',
            field=models.CharField(blank=True, choices=[('BCECE', 'BCECE'), ('DCECE', 'DCECE'), ('UG_BOTANY', 'UG BOTANY'), ('UG_ZOOLOGY', 'UG ZOOLOGY'), ('PG_BOTANY', 'PG BOTANY'), ('PG_ZOOLOGY', 'PG ZOOLOGY')], help_text='Select course category to filter batches', max_length=100, null=True, verbose_name='Course Category'),
        ),
    ]
