# Generated by Django 5.2.8 on 2025-11-11 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_alter_study_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='class_note',
            field=models.FileField(blank=True, help_text='Upload class notes (PDF or other)', null=True, upload_to='studies/notes/', verbose_name='Class Note'),
        ),
        migrations.AddField(
            model_name='study',
            name='dpp_make',
            field=models.FileField(blank=True, help_text='Upload DPP make file', null=True, upload_to='studies/dpp/make/', verbose_name='DPP Make'),
        ),
        migrations.AddField(
            model_name='study',
            name='dpp_pdf',
            field=models.FileField(blank=True, help_text='Upload DPP as PDF', null=True, upload_to='studies/dpp/pdf/', verbose_name='DPP PDF'),
        ),
        migrations.AddField(
            model_name='study',
            name='lecture_video',
            field=models.FileField(blank=True, help_text='Upload lecture video file', null=True, upload_to='studies/lectures/', verbose_name='Lecture Video'),
        ),
    ]
