# Generated by Django 4.2.7 on 2025-11-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0007_study_class_note_study_dpp_make_study_dpp_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='class_note',
            field=models.FileField(help_text='Upload class notes (PDF or other)', null=True, upload_to='studies/notes/', verbose_name='Class Note'),
        ),
        migrations.AlterField(
            model_name='study',
            name='lecture_video',
            field=models.FileField(help_text='Upload lecture video file', null=True, upload_to='studies/lectures/', verbose_name='Lecture Video'),
        ),
    ]
